mysql:
  #Host: go-mysql
  Host: localhost
  #ContainerName: go01_mysql
  Port: 3306
  User: root
  Password: 109339Lam@
  DBName: socialnetapp

redis:
  #Host: redis
  Host: localhost
  Port: 6379
  Password: ""
  DB: 0